# With this, I will create the pdf with photo and texts
# and then merge it with the other pdfs!
# https://www.google.fr/url?sa=t&rct=j&q=&esrc=s&source=web&cd=11&cad=rja&uact=8&ved=0ahUKEwjL6dv5gPbSAhWFlxoKHQZlBc8QFghTMAo&url=https%3A%2F%2Fwww.sitepoint.com%2Fpdf-generation-rails%2F&usg=AFQjCNGwKU2P02iigmii-NLa6mqYNxqR9w&sig2=ZTtiCBaxvTZeFfBFQVT_Yw
# http://prawnpdf.org/manual.pdf
# for images: http://stackoverflow.com/questions/11560455/prawn-import-image-from-url

# steps
# 1. Find a way to generate the pdf with the right photo, text, etc and have it generated by show.pdf
# 2. Then Find a way for this pdf not to be generated but merged with the other pdf
# 3. Find a way to make the URL a variable, this is not clean

require 'open-uri'

class MergedPdf < Prawn::Document

  def initialize(interview, user)
      super()
      @interview = interview
      @user = user
    end

  def generate
    #This inserts an image in the pdf file and sets the size of the image
    image (open ('http://res.cloudinary.com/di7e0fdiq/image/upload/' + @user.photo.path)), width: 100, height: 100

    # This inserts wanted text into the pdf
    y_position = cursor - 50

    # The bounding_box takes the x and y coordinates for positioning its content and some options to style it
    bounding_box([0, y_position], :width => 540, :height => 300) do
      text "My profile", size: 15, style: :bold
      text @user.first_name + ' ' + @user.last_name
    end
  end
end
